// NOTICE
// This file was automatically generated by ../../../generators/core.go. Do not edit it!
// You can regenerate it by running 'go generate ./core' from the directory above.

package model303

import (
	"github.com/crabmusket/gosunspec/core"
	"github.com/crabmusket/gosunspec/core/typelabel"
	"github.com/crabmusket/gosunspec/smdx"
)

// Block303 - Back of Module Temperature Model - Include to support variable number of  back of module temperature measurements

const (
	ModelID = 303
)

const (
	TmpBOM = "TmpBOM"
)

type Block303Repeat struct {
	TmpBOM int16 `sunspec:"offset=0,sf=-1"`
}

type Block303 struct {
	Repeats []Block303Repeat
}

func (self *Block303) GetId() core.ModelId {
	return ModelID
}

func init() {
	smdx.RegisterModel(&smdx.ModelElement{
		Id:     ModelID,
		Name:   "bom_temp",
		Length: 2,
		Blocks: []smdx.BlockElement{
			smdx.BlockElement{Name: "temp",
				Length: 1,
				Type:   "repeating",
				Points: []smdx.PointElement{
					smdx.PointElement{Id: TmpBOM, Offset: 0, Type: typelabel.Int16, ScaleFactor: "-1", Units: "C", Mandatory: true},
				},
			},
		}})
}
