// NOTICE
// This file was automatically generated by ../../generators/models.go. Do not edit it!
// You can regenerate it by running 'go generate ./models' from the directory above.

package model805

import (
	"github.com/crabmusket/gosunspec"
	"github.com/crabmusket/gosunspec/smdx"
	"github.com/crabmusket/gosunspec/typelabel"
)

// Block805 - Lithium-Ion Module Model -

const (
	ModelID = 805
)

const (
	CellSt         = "CellSt"
	CellTmp        = "CellTmp"
	CellTmpAvg     = "CellTmpAvg"
	CellTmpMax     = "CellTmpMax"
	CellTmpMaxCell = "CellTmpMaxCell"
	CellTmpMin     = "CellTmpMin"
	CellTmpMinCell = "CellTmpMinCell"
	CellV          = "CellV"
	CellVAvg       = "CellVAvg"
	CellVMax       = "CellVMax"
	CellVMaxCell   = "CellVMaxCell"
	CellVMin       = "CellVMin"
	CellVMinCell   = "CellVMinCell"
	CellV_SF       = "CellV_SF"
	DoD            = "DoD"
	DoD_SF         = "DoD_SF"
	Idx            = "Idx"
	NCell          = "NCell"
	NCellBal       = "NCellBal"
	NCyc           = "NCyc"
	Pad1           = "Pad1"
	SN             = "SN"
	SoC            = "SoC"
	SoC_SF         = "SoC_SF"
	SoH            = "SoH"
	SoH_SF         = "SoH_SF"
	Tmp_SF         = "Tmp_SF"
	V              = "V"
	V_SF           = "V_SF"
)

type Block805Repeat struct {
	CellV   uint16             `sunspec:"offset=0,sf=CellV_SF"`
	CellTmp int16              `sunspec:"offset=1,sf=Tmp_SF"`
	CellSt  sunspec.Bitfield32 `sunspec:"offset=2"`
}

type Block805 struct {
	Idx            uint16              `sunspec:"offset=0"`
	NCell          uint16              `sunspec:"offset=1"`
	SoC            uint16              `sunspec:"offset=2,sf=SoC_SF"`
	DoD            uint16              `sunspec:"offset=3,sf=DoD_SF"`
	NCyc           uint32              `sunspec:"offset=4"`
	SoH            uint16              `sunspec:"offset=6,sf=SoH_SF"`
	V              uint16              `sunspec:"offset=7,sf=V_SF"`
	CellVMax       uint16              `sunspec:"offset=8,sf=CellV_SF"`
	CellVMaxCell   uint16              `sunspec:"offset=9"`
	CellVMin       uint16              `sunspec:"offset=10,sf=CellV_SF"`
	CellVMinCell   uint16              `sunspec:"offset=11"`
	CellVAvg       uint16              `sunspec:"offset=12,sf=CellV_SF"`
	CellTmpMax     int16               `sunspec:"offset=13,sf=Tmp_SF"`
	CellTmpMaxCell uint16              `sunspec:"offset=14"`
	CellTmpMin     int16               `sunspec:"offset=15,sf=Tmp_SF"`
	CellTmpMinCell uint16              `sunspec:"offset=16"`
	CellTmpAvg     int16               `sunspec:"offset=17,sf=Tmp_SF"`
	SN             string              `sunspec:"offset=18,len=16"`
	NCellBal       uint16              `sunspec:"offset=34"`
	SoC_SF         sunspec.ScaleFactor `sunspec:"offset=35"`
	SoH_SF         sunspec.ScaleFactor `sunspec:"offset=36"`
	DoD_SF         sunspec.ScaleFactor `sunspec:"offset=37"`
	V_SF           sunspec.ScaleFactor `sunspec:"offset=38"`
	CellV_SF       sunspec.ScaleFactor `sunspec:"offset=39"`
	Tmp_SF         sunspec.ScaleFactor `sunspec:"offset=40"`
	Pad1           sunspec.Pad         `sunspec:"offset=41"`

	Repeats []Block805Repeat
}

func (self *Block805) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	smdx.RegisterModel(&smdx.ModelElement{
		Id:     ModelID,
		Name:   "lithium-ion-module",
		Length: 2,
		Blocks: []smdx.BlockElement{
			smdx.BlockElement{
				Length: 42,

				Points: []smdx.PointElement{
					smdx.PointElement{Id: Idx, Offset: 0, Type: typelabel.Uint16, Mandatory: true},
					smdx.PointElement{Id: NCell, Offset: 1, Type: typelabel.Uint16, Mandatory: true},
					smdx.PointElement{Id: SoC, Offset: 2, Type: typelabel.Uint16, ScaleFactor: "SoC_SF", Units: "%"},
					smdx.PointElement{Id: DoD, Offset: 3, Type: typelabel.Uint16, ScaleFactor: "DoD_SF", Units: "%"},
					smdx.PointElement{Id: NCyc, Offset: 4, Type: typelabel.Uint32},
					smdx.PointElement{Id: SoH, Offset: 6, Type: typelabel.Uint16, ScaleFactor: "SoH_SF", Units: "%"},
					smdx.PointElement{Id: V, Offset: 7, Type: typelabel.Uint16, ScaleFactor: "V_SF", Units: "V", Mandatory: true},
					smdx.PointElement{Id: CellVMax, Offset: 8, Type: typelabel.Uint16, ScaleFactor: "CellV_SF", Units: "V", Mandatory: true},
					smdx.PointElement{Id: CellVMaxCell, Offset: 9, Type: typelabel.Uint16},
					smdx.PointElement{Id: CellVMin, Offset: 10, Type: typelabel.Uint16, ScaleFactor: "CellV_SF", Units: "V", Mandatory: true},
					smdx.PointElement{Id: CellVMinCell, Offset: 11, Type: typelabel.Uint16},
					smdx.PointElement{Id: CellVAvg, Offset: 12, Type: typelabel.Uint16, ScaleFactor: "CellV_SF", Units: "V", Mandatory: true},
					smdx.PointElement{Id: CellTmpMax, Offset: 13, Type: typelabel.Int16, ScaleFactor: "Tmp_SF", Units: "C", Mandatory: true},
					smdx.PointElement{Id: CellTmpMaxCell, Offset: 14, Type: typelabel.Uint16},
					smdx.PointElement{Id: CellTmpMin, Offset: 15, Type: typelabel.Int16, ScaleFactor: "Tmp_SF", Units: "C", Mandatory: true},
					smdx.PointElement{Id: CellTmpMinCell, Offset: 16, Type: typelabel.Uint16},
					smdx.PointElement{Id: CellTmpAvg, Offset: 17, Type: typelabel.Int16, ScaleFactor: "Tmp_SF", Units: "C", Mandatory: true},
					smdx.PointElement{Id: SN, Offset: 18, Type: typelabel.String, Length: 16},
					smdx.PointElement{Id: NCellBal, Offset: 34, Type: typelabel.Uint16},
					smdx.PointElement{Id: SoC_SF, Offset: 35, Type: typelabel.Sunssf},
					smdx.PointElement{Id: SoH_SF, Offset: 36, Type: typelabel.Sunssf},
					smdx.PointElement{Id: DoD_SF, Offset: 37, Type: typelabel.Sunssf},
					smdx.PointElement{Id: V_SF, Offset: 38, Type: typelabel.Sunssf, Mandatory: true},
					smdx.PointElement{Id: CellV_SF, Offset: 39, Type: typelabel.Sunssf, Mandatory: true},
					smdx.PointElement{Id: Tmp_SF, Offset: 40, Type: typelabel.Sunssf, Mandatory: true},
					smdx.PointElement{Id: Pad1, Offset: 41, Type: typelabel.Pad, Mandatory: true},
				},
			},
			smdx.BlockElement{Name: "lithium-ion-module-cell",
				Length: 4,
				Type:   "repeating",
				Points: []smdx.PointElement{
					smdx.PointElement{Id: CellV, Offset: 0, Type: typelabel.Uint16, ScaleFactor: "CellV_SF", Units: "V", Mandatory: true},
					smdx.PointElement{Id: CellTmp, Offset: 1, Type: typelabel.Int16, ScaleFactor: "Tmp_SF", Units: "C", Mandatory: true},
					smdx.PointElement{Id: CellSt, Offset: 2, Type: typelabel.Bitfield32},
				},
			},
		}})
}
