// NOTICE
// This file was automatically generated by ../../../generators/core.go. Do not edit it!
// You can regenerate it by running 'go generate ./core' from the directory above.

package model807

import (
	"github.com/crabmusket/gosunspec/core"
	"github.com/crabmusket/gosunspec/smdx"
)

// Block807 - Flow Battery String Model -

const (
	ModelID = 807
)

const (
	CellVAvg        = "CellVAvg"
	CellVMax        = "CellVMax"
	CellVMaxMod     = "CellVMaxMod"
	CellVMaxStk     = "CellVMaxStk"
	CellVMin        = "CellVMin"
	CellVMinMod     = "CellVMinMod"
	CellVMinStk     = "CellVMinStk"
	CellV_SF        = "CellV_SF"
	Evt1            = "Evt1"
	Evt2            = "Evt2"
	EvtVnd1         = "EvtVnd1"
	EvtVnd2         = "EvtVnd2"
	Idx             = "Idx"
	ModAnoTmp       = "ModAnoTmp"
	ModCatTmp       = "ModCatTmp"
	ModCellVAvg     = "ModCellVAvg"
	ModCellVMax     = "ModCellVMax"
	ModCellVMaxCell = "ModCellVMaxCell"
	ModCellVMin     = "ModCellVMin"
	ModCellVMinCell = "ModCellVMinCell"
	ModConFail      = "ModConFail"
	ModConSt        = "ModConSt"
	ModEvt1         = "ModEvt1"
	ModEvt2         = "ModEvt2"
	ModIdx          = "ModIdx"
	ModNStk         = "ModNStk"
	ModOCV          = "ModOCV"
	ModSetCon       = "ModSetCon"
	ModSetEna       = "ModSetEna"
	ModSoC          = "ModSoC"
	ModSt           = "ModSt"
	ModV            = "ModV"
	ModVAvg         = "ModVAvg"
	ModVMax         = "ModVMax"
	ModVMaxMod      = "ModVMaxMod"
	ModVMin         = "ModVMin"
	ModVMinMod      = "ModVMinMod"
	ModV_SF         = "ModV_SF"
	NMod            = "NMod"
	NModCon         = "NModCon"
	OCV_SF          = "OCV_SF"
	Pad1            = "Pad1"
	Pad4            = "Pad4"
	SoC_SF          = "SoC_SF"
	TmpAvg          = "TmpAvg"
	TmpMax          = "TmpMax"
	TmpMaxMod       = "TmpMaxMod"
	TmpMin          = "TmpMin"
	TmpMinMod       = "TmpMinMod"
	Tmp_SF          = "Tmp_SF"
)

type Block807Repeat struct {
	ModIdx          uint16          `sunspec:"offset=0"`
	ModNStk         uint16          `sunspec:"offset=1"`
	ModSt           core.Bitfield32 `sunspec:"offset=2"`
	ModSoC          uint16          `sunspec:"offset=4,sf=SoC_SF"`
	ModOCV          uint16          `sunspec:"offset=5,sf=OCV_SF"`
	ModV            uint16          `sunspec:"offset=6,sf=ModV_SF"`
	ModCellVMax     uint16          `sunspec:"offset=7,sf=CellV_SF"`
	ModCellVMaxCell uint16          `sunspec:"offset=8"`
	ModCellVMin     uint16          `sunspec:"offset=9,sf=CellV_SF"`
	ModCellVMinCell uint16          `sunspec:"offset=10"`
	ModCellVAvg     uint16          `sunspec:"offset=11,sf=CellV_SF"`
	ModAnoTmp       uint16          `sunspec:"offset=12,sf=Tmp_SF"`
	ModCatTmp       uint16          `sunspec:"offset=13,sf=Tmp_SF"`
	ModConSt        core.Bitfield32 `sunspec:"offset=14"`
	ModEvt1         core.Bitfield32 `sunspec:"offset=16"`
	ModEvt2         core.Bitfield32 `sunspec:"offset=18"`
	ModConFail      core.Enum16     `sunspec:"offset=20"`
	ModSetEna       core.Enum16     `sunspec:"offset=21,access=rw"`
	ModSetCon       core.Enum16     `sunspec:"offset=22,access=rw"`
	Pad4            core.Pad        `sunspec:"offset=23"`
}

type Block807 struct {
	Idx         uint16           `sunspec:"offset=0"`
	NMod        uint16           `sunspec:"offset=1"`
	NModCon     uint16           `sunspec:"offset=2"`
	ModVMax     uint16           `sunspec:"offset=3,sf=ModV_SF"`
	ModVMaxMod  uint16           `sunspec:"offset=4"`
	ModVMin     uint16           `sunspec:"offset=5,sf=ModV_SF"`
	ModVMinMod  uint16           `sunspec:"offset=6"`
	ModVAvg     uint16           `sunspec:"offset=7,sf=ModV_SF"`
	CellVMax    uint16           `sunspec:"offset=8,sf=CellV_SF"`
	CellVMaxMod uint16           `sunspec:"offset=9"`
	CellVMaxStk uint16           `sunspec:"offset=10"`
	CellVMin    uint16           `sunspec:"offset=11,sf=CellV_SF"`
	CellVMinMod uint16           `sunspec:"offset=12"`
	CellVMinStk uint16           `sunspec:"offset=13"`
	CellVAvg    uint16           `sunspec:"offset=14,sf=CellV_SF"`
	TmpMax      int16            `sunspec:"offset=15,sf=Tmp_SF"`
	TmpMaxMod   uint16           `sunspec:"offset=16"`
	TmpMin      int16            `sunspec:"offset=17,sf=Tmp_SF"`
	TmpMinMod   uint16           `sunspec:"offset=18"`
	TmpAvg      int16            `sunspec:"offset=19,sf=Tmp_SF"`
	Evt1        core.Bitfield32  `sunspec:"offset=20"`
	Evt2        core.Bitfield32  `sunspec:"offset=22"`
	EvtVnd1     core.Bitfield32  `sunspec:"offset=24"`
	EvtVnd2     core.Bitfield32  `sunspec:"offset=26"`
	ModV_SF     core.ScaleFactor `sunspec:"offset=28"`
	CellV_SF    core.ScaleFactor `sunspec:"offset=29"`
	Tmp_SF      core.ScaleFactor `sunspec:"offset=30"`
	SoC_SF      core.ScaleFactor `sunspec:"offset=31"`
	OCV_SF      core.ScaleFactor `sunspec:"offset=32"`
	Pad1        core.Pad         `sunspec:"offset=33"`

	Repeats []Block807Repeat
}

func (self *Block807) GetId() core.ModelId {
	return ModelID
}

func init() {
	smdx.RegisterModel(&smdx.ModelElement{
		Id:     ModelID,
		Name:   "flow_battery_string",
		Length: 36,
		Blocks: []smdx.BlockElement{
			smdx.BlockElement{
				Length: 34,

				Points: []smdx.PointElement{
					smdx.PointElement{Id: Idx, Offset: 0, Type: "uint16", Mandatory: true},
					smdx.PointElement{Id: NMod, Offset: 1, Type: "uint16", Mandatory: true},
					smdx.PointElement{Id: NModCon, Offset: 2, Type: "uint16", Mandatory: true},
					smdx.PointElement{Id: ModVMax, Offset: 3, Type: "uint16", ScaleFactor: "ModV_SF", Units: "V", Mandatory: true},
					smdx.PointElement{Id: ModVMaxMod, Offset: 4, Type: "uint16"},
					smdx.PointElement{Id: ModVMin, Offset: 5, Type: "uint16", ScaleFactor: "ModV_SF", Units: "V", Mandatory: true},
					smdx.PointElement{Id: ModVMinMod, Offset: 6, Type: "uint16"},
					smdx.PointElement{Id: ModVAvg, Offset: 7, Type: "uint16", ScaleFactor: "ModV_SF", Units: "V", Mandatory: true},
					smdx.PointElement{Id: CellVMax, Offset: 8, Type: "uint16", ScaleFactor: "CellV_SF", Units: "V", Mandatory: true},
					smdx.PointElement{Id: CellVMaxMod, Offset: 9, Type: "uint16"},
					smdx.PointElement{Id: CellVMaxStk, Offset: 10, Type: "uint16"},
					smdx.PointElement{Id: CellVMin, Offset: 11, Type: "uint16", ScaleFactor: "CellV_SF", Units: "V", Mandatory: true},
					smdx.PointElement{Id: CellVMinMod, Offset: 12, Type: "uint16"},
					smdx.PointElement{Id: CellVMinStk, Offset: 13, Type: "uint16"},
					smdx.PointElement{Id: CellVAvg, Offset: 14, Type: "uint16", ScaleFactor: "CellV_SF", Units: "V", Mandatory: true},
					smdx.PointElement{Id: TmpMax, Offset: 15, Type: "int16", ScaleFactor: "Tmp_SF", Units: "C", Mandatory: true},
					smdx.PointElement{Id: TmpMaxMod, Offset: 16, Type: "uint16"},
					smdx.PointElement{Id: TmpMin, Offset: 17, Type: "int16", ScaleFactor: "Tmp_SF", Units: "C", Mandatory: true},
					smdx.PointElement{Id: TmpMinMod, Offset: 18, Type: "uint16"},
					smdx.PointElement{Id: TmpAvg, Offset: 19, Type: "int16", ScaleFactor: "Tmp_SF", Units: "C", Mandatory: true},
					smdx.PointElement{Id: Evt1, Offset: 20, Type: "bitfield32", Mandatory: true},
					smdx.PointElement{Id: Evt2, Offset: 22, Type: "bitfield32", Mandatory: true},
					smdx.PointElement{Id: EvtVnd1, Offset: 24, Type: "bitfield32", Mandatory: true},
					smdx.PointElement{Id: EvtVnd2, Offset: 26, Type: "bitfield32", Mandatory: true},
					smdx.PointElement{Id: ModV_SF, Offset: 28, Type: "sunssf", Mandatory: true},
					smdx.PointElement{Id: CellV_SF, Offset: 29, Type: "sunssf", Mandatory: true},
					smdx.PointElement{Id: Tmp_SF, Offset: 30, Type: "sunssf", Mandatory: true},
					smdx.PointElement{Id: SoC_SF, Offset: 31, Type: "sunssf", Mandatory: true},
					smdx.PointElement{Id: OCV_SF, Offset: 32, Type: "sunssf", Mandatory: true},
					smdx.PointElement{Id: Pad1, Offset: 33, Type: "pad", Mandatory: true},
				},
			},
			smdx.BlockElement{Name: "module",
				Length: 24,
				Type:   "repeating",
				Points: []smdx.PointElement{
					smdx.PointElement{Id: ModIdx, Offset: 0, Type: "uint16", Mandatory: true},
					smdx.PointElement{Id: ModNStk, Offset: 1, Type: "uint16", Mandatory: true},
					smdx.PointElement{Id: ModSt, Offset: 2, Type: "bitfield32", Mandatory: true},
					smdx.PointElement{Id: ModSoC, Offset: 4, Type: "uint16", ScaleFactor: "SoC_SF", Units: "%", Mandatory: true},
					smdx.PointElement{Id: ModOCV, Offset: 5, Type: "uint16", ScaleFactor: "OCV_SF", Units: "V", Mandatory: true},
					smdx.PointElement{Id: ModV, Offset: 6, Type: "uint16", ScaleFactor: "ModV_SF", Units: "V", Mandatory: true},
					smdx.PointElement{Id: ModCellVMax, Offset: 7, Type: "uint16", ScaleFactor: "CellV_SF", Units: "V", Mandatory: true},
					smdx.PointElement{Id: ModCellVMaxCell, Offset: 8, Type: "uint16"},
					smdx.PointElement{Id: ModCellVMin, Offset: 9, Type: "uint16", ScaleFactor: "CellV_SF", Units: "V", Mandatory: true},
					smdx.PointElement{Id: ModCellVMinCell, Offset: 10, Type: "uint16"},
					smdx.PointElement{Id: ModCellVAvg, Offset: 11, Type: "uint16", ScaleFactor: "CellV_SF", Units: "V", Mandatory: true},
					smdx.PointElement{Id: ModAnoTmp, Offset: 12, Type: "uint16", ScaleFactor: "Tmp_SF", Units: "C"},
					smdx.PointElement{Id: ModCatTmp, Offset: 13, Type: "uint16", ScaleFactor: "Tmp_SF", Units: "C"},
					smdx.PointElement{Id: ModConSt, Offset: 14, Type: "bitfield32"},
					smdx.PointElement{Id: ModEvt1, Offset: 16, Type: "bitfield32", Mandatory: true},
					smdx.PointElement{Id: ModEvt2, Offset: 18, Type: "bitfield32", Mandatory: true},
					smdx.PointElement{Id: ModConFail, Offset: 20, Type: "enum16"},
					smdx.PointElement{Id: ModSetEna, Offset: 21, Type: "enum16", Access: "rw"},
					smdx.PointElement{Id: ModSetCon, Offset: 22, Type: "enum16", Access: "rw"},
					smdx.PointElement{Id: Pad4, Offset: 23, Type: "pad", Mandatory: true},
				},
			},
		}})
}
