// NOTICE
// This file was automatically generated by ../../../generators/core.go. Do not edit it!
// You can regenerate it by running 'go generate ./core' from the directory above.

package model14

import (
	"github.com/crabmusket/gosunspec/core"
	"github.com/crabmusket/gosunspec/smdx"
)

// Block14 - Proxy Server - Include this block to allow for a proxy server

const (
	ModelID = 14
)

const (
	Addr = "Addr"
	Cap  = "Cap"
	Cfg  = "Cfg"
	Nam  = "Nam"
	Port = "Port"
	Pw   = "Pw"
	Typ  = "Typ"
	User = "User"
)

type Block14 struct {
	Nam  core.String     `sunspec:"offset=0,len=4,access=rw"`
	Cap  core.Bitfield16 `sunspec:"offset=4,access=rw"`
	Cfg  core.Enum16     `sunspec:"offset=5,access=rw"`
	Typ  core.Bitfield16 `sunspec:"offset=6,access=rw"`
	Addr core.String     `sunspec:"offset=7,len=20,access=rw"`
	Port uint16          `sunspec:"offset=27,access=rw"`
	User core.String     `sunspec:"offset=28,len=12,access=rw"`
	Pw   core.String     `sunspec:"offset=40,len=12,access=rw"`
}

func (self *Block14) GetId() core.ModelId {
	return ModelID
}

func init() {
	smdx.RegisterModel(&smdx.ModelElement{
		Id:     ModelID,
		Name:   "",
		Length: 52,
		Blocks: []smdx.BlockElement{
			smdx.BlockElement{
				Length: 52,

				Points: []smdx.PointElement{
					smdx.PointElement{Id: Nam, Offset: 0, Type: "string", Access: "rw", Length: 4},
					smdx.PointElement{Id: Cap, Offset: 4, Type: "bitfield16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Cfg, Offset: 5, Type: "enum16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Typ, Offset: 6, Type: "bitfield16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Addr, Offset: 7, Type: "string", Access: "rw", Length: 20, Mandatory: true},
					smdx.PointElement{Id: Port, Offset: 27, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: User, Offset: 28, Type: "string", Access: "rw", Length: 12},
					smdx.PointElement{Id: Pw, Offset: 40, Type: "string", Access: "rw", Length: 12},
				},
			},
		}})
}
