// NOTICE
// This file was automatically generated by ../../../generators/core.go. Do not edit it!
// You can regenerate it by running 'go generate ./core' from the directory above.

package model15

import (
	"github.com/crabmusket/gosunspec/core"
	"github.com/crabmusket/gosunspec/smdx"
)

// Block15 - Interface Counters Model - Interface counters

const (
	ModelID = 15
)

const (
	Clr       = "Clr"
	InCnt     = "InCnt"
	InDscCnt  = "InDscCnt"
	InErrCnt  = "InErrCnt"
	InNUcCnt  = "InNUcCnt"
	InUcCnt   = "InUcCnt"
	InUnkCnt  = "InUnkCnt"
	OutCnt    = "OutCnt"
	OutDscCnt = "OutDscCnt"
	OutErrCnt = "OutErrCnt"
	OutNUcCnt = "OutNUcCnt"
	OutUcCnt  = "OutUcCnt"
	Pad       = "Pad"
)

type Block15 struct {
	Clr       uint16     `sunspec:"offset=0,access=rw"`
	InCnt     core.Acc32 `sunspec:"offset=1"`
	InUcCnt   core.Acc32 `sunspec:"offset=3"`
	InNUcCnt  core.Acc32 `sunspec:"offset=5"`
	InDscCnt  core.Acc32 `sunspec:"offset=7"`
	InErrCnt  core.Acc32 `sunspec:"offset=9"`
	InUnkCnt  core.Acc32 `sunspec:"offset=11"`
	OutCnt    core.Acc32 `sunspec:"offset=13"`
	OutUcCnt  core.Acc32 `sunspec:"offset=15"`
	OutNUcCnt core.Acc32 `sunspec:"offset=17"`
	OutDscCnt core.Acc32 `sunspec:"offset=19"`
	OutErrCnt core.Acc32 `sunspec:"offset=21"`
	Pad       core.Pad   `sunspec:"offset=23"`
}

func (self *Block15) GetId() core.ModelId {
	return ModelID
}

func init() {
	smdx.RegisterModel(&smdx.ModelElement{
		Id:     ModelID,
		Name:   "",
		Length: 24,
		Blocks: []smdx.BlockElement{
			smdx.BlockElement{
				Length: 24,

				Points: []smdx.PointElement{
					smdx.PointElement{Id: Clr, Offset: 0, Type: "uint16", Access: "rw"},
					smdx.PointElement{Id: InCnt, Offset: 1, Type: "acc32"},
					smdx.PointElement{Id: InUcCnt, Offset: 3, Type: "acc32"},
					smdx.PointElement{Id: InNUcCnt, Offset: 5, Type: "acc32"},
					smdx.PointElement{Id: InDscCnt, Offset: 7, Type: "acc32"},
					smdx.PointElement{Id: InErrCnt, Offset: 9, Type: "acc32"},
					smdx.PointElement{Id: InUnkCnt, Offset: 11, Type: "acc32"},
					smdx.PointElement{Id: OutCnt, Offset: 13, Type: "acc32"},
					smdx.PointElement{Id: OutUcCnt, Offset: 15, Type: "acc32"},
					smdx.PointElement{Id: OutNUcCnt, Offset: 17, Type: "acc32"},
					smdx.PointElement{Id: OutDscCnt, Offset: 19, Type: "acc32"},
					smdx.PointElement{Id: OutErrCnt, Offset: 21, Type: "acc32"},
					smdx.PointElement{Id: Pad, Offset: 23, Type: "pad"},
				},
			},
		}})
}
