// NOTICE
// This file was automatically generated by ../../../generators/core.go. Do not edit it!
// You can regenerate it by running 'go generate ./core' from the directory above.

package model5

import (
	"github.com/crabmusket/gosunspec/core"
	"github.com/crabmusket/gosunspec/smdx"
)

// Block5 - Secure Write Request - Include a digial signature along with the control data

const (
	ModelID = 5
)

const (
	Alg   = "Alg"
	DS    = "DS"
	Ms    = "Ms"
	N     = "N"
	Off1  = "Off1"
	Off10 = "Off10"
	Off11 = "Off11"
	Off12 = "Off12"
	Off13 = "Off13"
	Off14 = "Off14"
	Off15 = "Off15"
	Off16 = "Off16"
	Off17 = "Off17"
	Off18 = "Off18"
	Off19 = "Off19"
	Off2  = "Off2"
	Off20 = "Off20"
	Off21 = "Off21"
	Off22 = "Off22"
	Off23 = "Off23"
	Off24 = "Off24"
	Off25 = "Off25"
	Off26 = "Off26"
	Off27 = "Off27"
	Off28 = "Off28"
	Off29 = "Off29"
	Off3  = "Off3"
	Off30 = "Off30"
	Off31 = "Off31"
	Off32 = "Off32"
	Off33 = "Off33"
	Off34 = "Off34"
	Off35 = "Off35"
	Off36 = "Off36"
	Off37 = "Off37"
	Off38 = "Off38"
	Off39 = "Off39"
	Off4  = "Off4"
	Off40 = "Off40"
	Off5  = "Off5"
	Off6  = "Off6"
	Off7  = "Off7"
	Off8  = "Off8"
	Off9  = "Off9"
	Role  = "Role"
	Seq   = "Seq"
	Ts    = "Ts"
	Val1  = "Val1"
	Val10 = "Val10"
	Val11 = "Val11"
	Val12 = "Val12"
	Val13 = "Val13"
	Val14 = "Val14"
	Val15 = "Val15"
	Val16 = "Val16"
	Val17 = "Val17"
	Val18 = "Val18"
	Val19 = "Val19"
	Val2  = "Val2"
	Val20 = "Val20"
	Val21 = "Val21"
	Val22 = "Val22"
	Val23 = "Val23"
	Val24 = "Val24"
	Val25 = "Val25"
	Val26 = "Val26"
	Val27 = "Val27"
	Val28 = "Val28"
	Val29 = "Val29"
	Val3  = "Val3"
	Val30 = "Val30"
	Val31 = "Val31"
	Val32 = "Val32"
	Val33 = "Val33"
	Val34 = "Val34"
	Val35 = "Val35"
	Val36 = "Val36"
	Val37 = "Val37"
	Val38 = "Val38"
	Val39 = "Val39"
	Val4  = "Val4"
	Val40 = "Val40"
	Val5  = "Val5"
	Val6  = "Val6"
	Val7  = "Val7"
	Val8  = "Val8"
	Val9  = "Val9"
	X     = "X"
)

type Block5Repeat struct {
	DS uint16 `sunspec:"offset=0,access=rw"`
}

type Block5 struct {
	X     uint16      `sunspec:"offset=0,access=rw"`
	Off1  uint16      `sunspec:"offset=1,access=rw"`
	Val1  uint16      `sunspec:"offset=2,access=rw"`
	Off2  uint16      `sunspec:"offset=3,access=rw"`
	Val2  uint16      `sunspec:"offset=4,access=rw"`
	Off3  uint16      `sunspec:"offset=5,access=rw"`
	Val3  uint16      `sunspec:"offset=6,access=rw"`
	Off4  uint16      `sunspec:"offset=7,access=rw"`
	Val4  uint16      `sunspec:"offset=8,access=rw"`
	Off5  uint16      `sunspec:"offset=9,access=rw"`
	Val5  uint16      `sunspec:"offset=10,access=rw"`
	Off6  uint16      `sunspec:"offset=11,access=rw"`
	Val6  uint16      `sunspec:"offset=12,access=rw"`
	Off7  uint16      `sunspec:"offset=13,access=rw"`
	Val7  uint16      `sunspec:"offset=14,access=rw"`
	Off8  uint16      `sunspec:"offset=15,access=rw"`
	Val8  uint16      `sunspec:"offset=16,access=rw"`
	Off9  uint16      `sunspec:"offset=17,access=rw"`
	Val9  uint16      `sunspec:"offset=18,access=rw"`
	Off10 uint16      `sunspec:"offset=19,access=rw"`
	Val10 uint16      `sunspec:"offset=20,access=rw"`
	Off11 uint16      `sunspec:"offset=21,access=rw"`
	Val11 uint16      `sunspec:"offset=22,access=rw"`
	Off12 uint16      `sunspec:"offset=23,access=rw"`
	Val12 uint16      `sunspec:"offset=24,access=rw"`
	Off13 uint16      `sunspec:"offset=25,access=rw"`
	Val13 uint16      `sunspec:"offset=26,access=rw"`
	Off14 uint16      `sunspec:"offset=27,access=rw"`
	Val14 uint16      `sunspec:"offset=28,access=rw"`
	Off15 uint16      `sunspec:"offset=29,access=rw"`
	Val15 uint16      `sunspec:"offset=30,access=rw"`
	Off16 uint16      `sunspec:"offset=31,access=rw"`
	Val16 uint16      `sunspec:"offset=32,access=rw"`
	Off17 uint16      `sunspec:"offset=33,access=rw"`
	Val17 uint16      `sunspec:"offset=34,access=rw"`
	Off18 uint16      `sunspec:"offset=35,access=rw"`
	Val18 uint16      `sunspec:"offset=36,access=rw"`
	Off19 uint16      `sunspec:"offset=37,access=rw"`
	Val19 uint16      `sunspec:"offset=38,access=rw"`
	Off20 uint16      `sunspec:"offset=39,access=rw"`
	Val20 uint16      `sunspec:"offset=40,access=rw"`
	Off21 uint16      `sunspec:"offset=41,access=rw"`
	Val21 uint16      `sunspec:"offset=42,access=rw"`
	Off22 uint16      `sunspec:"offset=43,access=rw"`
	Val22 uint16      `sunspec:"offset=44,access=rw"`
	Off23 uint16      `sunspec:"offset=45,access=rw"`
	Val23 uint16      `sunspec:"offset=46,access=rw"`
	Off24 uint16      `sunspec:"offset=47,access=rw"`
	Val24 uint16      `sunspec:"offset=48,access=rw"`
	Off25 uint16      `sunspec:"offset=49,access=rw"`
	Val25 uint16      `sunspec:"offset=50,access=rw"`
	Off26 uint16      `sunspec:"offset=51,access=rw"`
	Val26 uint16      `sunspec:"offset=52,access=rw"`
	Off27 uint16      `sunspec:"offset=53,access=rw"`
	Val27 uint16      `sunspec:"offset=54,access=rw"`
	Off28 uint16      `sunspec:"offset=55,access=rw"`
	Val28 uint16      `sunspec:"offset=56,access=rw"`
	Off29 uint16      `sunspec:"offset=57,access=rw"`
	Val29 uint16      `sunspec:"offset=58,access=rw"`
	Off30 uint16      `sunspec:"offset=59,access=rw"`
	Val30 uint16      `sunspec:"offset=60,access=rw"`
	Off31 uint16      `sunspec:"offset=61,access=rw"`
	Val31 uint16      `sunspec:"offset=62,access=rw"`
	Off32 uint16      `sunspec:"offset=63,access=rw"`
	Val32 uint16      `sunspec:"offset=64,access=rw"`
	Off33 uint16      `sunspec:"offset=65,access=rw"`
	Val33 uint16      `sunspec:"offset=66,access=rw"`
	Off34 uint16      `sunspec:"offset=67,access=rw"`
	Val34 uint16      `sunspec:"offset=68,access=rw"`
	Off35 uint16      `sunspec:"offset=69,access=rw"`
	Val35 uint16      `sunspec:"offset=70,access=rw"`
	Off36 uint16      `sunspec:"offset=71,access=rw"`
	Val36 uint16      `sunspec:"offset=72,access=rw"`
	Off37 uint16      `sunspec:"offset=73,access=rw"`
	Val37 uint16      `sunspec:"offset=74,access=rw"`
	Off38 uint16      `sunspec:"offset=75,access=rw"`
	Val38 uint16      `sunspec:"offset=76,access=rw"`
	Off39 uint16      `sunspec:"offset=77,access=rw"`
	Val39 uint16      `sunspec:"offset=78,access=rw"`
	Off40 uint16      `sunspec:"offset=79,access=rw"`
	Val40 uint16      `sunspec:"offset=80,access=rw"`
	Ts    uint32      `sunspec:"offset=81,access=rw"`
	Ms    uint16      `sunspec:"offset=83,access=rw"`
	Seq   uint16      `sunspec:"offset=84,access=rw"`
	Role  uint16      `sunspec:"offset=85,access=rw"`
	Alg   core.Enum16 `sunspec:"offset=86,access=rw"`
	N     uint16      `sunspec:"offset=87,access=rw"`

	Repeats []Block5Repeat
}

func (self *Block5) GetId() core.ModelId {
	return ModelID
}

func init() {
	smdx.RegisterModel(&smdx.ModelElement{
		Id:     ModelID,
		Name:   "",
		Length: 89,
		Blocks: []smdx.BlockElement{
			smdx.BlockElement{
				Length: 88,

				Points: []smdx.PointElement{
					smdx.PointElement{Id: X, Offset: 0, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off1, Offset: 1, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val1, Offset: 2, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off2, Offset: 3, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val2, Offset: 4, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off3, Offset: 5, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val3, Offset: 6, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off4, Offset: 7, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val4, Offset: 8, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off5, Offset: 9, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val5, Offset: 10, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off6, Offset: 11, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val6, Offset: 12, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off7, Offset: 13, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val7, Offset: 14, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off8, Offset: 15, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val8, Offset: 16, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off9, Offset: 17, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val9, Offset: 18, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off10, Offset: 19, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val10, Offset: 20, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off11, Offset: 21, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val11, Offset: 22, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off12, Offset: 23, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val12, Offset: 24, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off13, Offset: 25, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val13, Offset: 26, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off14, Offset: 27, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val14, Offset: 28, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off15, Offset: 29, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val15, Offset: 30, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off16, Offset: 31, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val16, Offset: 32, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off17, Offset: 33, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val17, Offset: 34, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off18, Offset: 35, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val18, Offset: 36, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off19, Offset: 37, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val19, Offset: 38, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off20, Offset: 39, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val20, Offset: 40, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off21, Offset: 41, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val21, Offset: 42, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off22, Offset: 43, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val22, Offset: 44, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off23, Offset: 45, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val23, Offset: 46, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off24, Offset: 47, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val24, Offset: 48, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off25, Offset: 49, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val25, Offset: 50, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off26, Offset: 51, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val26, Offset: 52, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off27, Offset: 53, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val27, Offset: 54, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off28, Offset: 55, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val28, Offset: 56, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off29, Offset: 57, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val29, Offset: 58, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off30, Offset: 59, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val30, Offset: 60, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off31, Offset: 61, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val31, Offset: 62, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off32, Offset: 63, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val32, Offset: 64, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off33, Offset: 65, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val33, Offset: 66, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off34, Offset: 67, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val34, Offset: 68, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off35, Offset: 69, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val35, Offset: 70, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off36, Offset: 71, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val36, Offset: 72, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off37, Offset: 73, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val37, Offset: 74, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off38, Offset: 75, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val38, Offset: 76, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off39, Offset: 77, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val39, Offset: 78, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Off40, Offset: 79, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Val40, Offset: 80, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Ts, Offset: 81, Type: "uint32", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Ms, Offset: 83, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Seq, Offset: 84, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Role, Offset: 85, Type: "uint16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: Alg, Offset: 86, Type: "enum16", Access: "rw", Mandatory: true},
					smdx.PointElement{Id: N, Offset: 87, Type: "uint16", Access: "rw", Mandatory: true},
				},
			},
			smdx.BlockElement{
				Length: 1,
				Type:   "repeating",
				Points: []smdx.PointElement{
					smdx.PointElement{Id: DS, Offset: 0, Type: "uint16", Access: "rw"},
				},
			},
		}})
}
