package main

import (
	"github.com/crabmusket/gosunspec/smdx"
	"io/ioutil"
	"log"
	"os"
	"os/exec"
	"strings"
	"text/template"
)

const file = `
{{define "point"}}{{.Id}} {{.Type|goType}} ` + "`" + `sunspec:"offset={{.Offset}}{{if gt .Length 0}},len={{.Length}}{{end}}{{if ne .ScaleFactor ""}},sf={{.ScaleFactor}}{{end}}{{if ne .Access ""}},access={{.Access}}{{end}}"` + "`" + `{{end}}
{{define "model"}}
{{$model := index .Models 0 }}
{{$strings := index .Strings 0 }}

// Block{{$model.Id}} - {{$strings.ModelStrings.Label}} - {{$strings.ModelStrings.Description}}
{{range (repeatingBlocks $model)}}
type Block{{$model.Id}}Repeat struct {
	{{range .Points}}{{template "point" .}}
{{end}}
}
{{end}}

type Block{{$model.Id}} struct {
{{range (fixedBlocks $model)}}
{{range .Points}}    {{template "point" .}}
{{end}}
	{{end}}
{{range (repeatingBlocks $model)}}
  Repeats []Block{{$model.Id}}Repeat
{{end}}
}

func (self *Block{{$model.Id}}) GetId() ModelId {
  return {{$model.Id}}
}

func init() {
	smdx.RegisterModel(&smdx.ModelElement{
	Id: {{$model.Id}},
	Name: "{{$model.Name}}",
	Length: {{$model.Length}},
	Blocks: []smdx.BlockElement{ {{range $model.Blocks}}
			smdx.BlockElement{ {{if gt (len .Name) 0 }}Name: "{{.Name}}",{{end}}
				Length: {{.Length}},
				{{if gt (len .Type) 0 }}Type: "{{.Type}}",{{end}}
				Points: []smdx.PointElement{ {{range .Points}}
					smdx.PointElement{Id: "{{.Id}}",Offset: {{.Offset}},Type: "{{.Type}}"{{optF "ScaleFactor" .ScaleFactor}}{{optF "Units" .Units}}{{optF "Access" .Access}}{{if gt (.Length) 0}},Length: {{.Length}}{{end}}{{if .Mandatory}},Mandatory: {{.Mandatory}}{{end}},}, {{end}}
				},
			}, {{end}}
	}})
}
{{end}}
// NOTICE
// This file was automatically generated by ../generators/core.go. Do not edit it!
// You can regenerate it by running 'go generate ./core' from the directory above.

package core

import (
	"github.com/crabmusket/gosunspec/smdx"
)

{{range .Models}}
{{template "model" .}}
{{end}}
`

func main() {

	smdxDir := "../models/smdx/"
	files, err := ioutil.ReadDir(smdxDir)
	if err != nil {
		log.Fatal(err)
	}

	models := []smdx.ModelDefinitionElement{}
	for _, file := range files {
		if strings.HasPrefix(file.Name(), "smdx_") {
			smdxFile, err := os.OpenFile(smdxDir+file.Name(), os.O_RDONLY, 0644)
			if err != nil {
				log.Fatal(err)
			}

			def, err := smdx.FromXML(smdxFile)
			if err != nil {
				smdxFile.Close()
				log.Fatal(err)
			}
			smdxFile.Close()

			if len(def.Models) < 1 {
				continue
			} else {
				models = append(models, def)
			}
		}
	}

	t := template.New("file")
	t.Funcs(map[string]interface{}{
		"goType": func(sstype string) string {
			switch sstype {
			case "uint16", "uint32", "uint64", "int16", "float32", "int32", "int64":
				return sstype
			case "sunssf":
				return "ScaleFactor"
			case "eui48":
				return strings.ToUpper(sstype)
			default:
				return strings.Title(sstype)
			}
		},
		"repeatingBlocks": func(m smdx.ModelElement) []smdx.BlockElement {
			if len(m.Blocks) == 1 && m.Blocks[0].Type == "repeating" {
				return m.Blocks
			} else if len(m.Blocks) > 1 {
				return m.Blocks[1:]
			} else {
				return []smdx.BlockElement{}
			}
		},
		"fixedBlocks": func(m smdx.ModelElement) []smdx.BlockElement {
			if len(m.Blocks) > 0 && m.Blocks[0].Type != "repeating" {
				return m.Blocks[0:1]
			} else {
				return []smdx.BlockElement{}
			}
		},
		"optF": func(n, v string) string {
			if len(v) > 0 {
				return "," + n + ": \"" + v + "\""
			} else {
				return ""
			}
		},
	})
	modelTemplate := template.Must(t.Parse(file))

	outputFilename := "../core/models.go.tmp"
	outputFile, err := os.OpenFile(outputFilename, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0644)
	if err != nil {
		log.Fatal(err)
	}
	if err := modelTemplate.Execute(outputFile, map[string]interface{}{
		"Models": models,
	}); err != nil {
		log.Fatalf("template execution failed: %v", err)
	}
	outputFile.Close()

	cmd := exec.Command("/bin/sh", "-c", "gofmt -w "+outputFilename)
	if err := cmd.Run(); err != nil {
		log.Fatalf("gofmt failed: %v", err)
	}
	if err := os.Rename("../core/models.go.tmp", "../core/models.go"); err != nil {
		log.Fatalf("replacing models.go failed: %v", err)
	}
}
