package main

import (
	"io/ioutil"
)

func main() {
	preamble := []byte(`// This file was automatically generated by generatoes/models.go.
// Do not edit it, but run 'go generate' to recreate it.

package gosunspec
`)
	_ = ioutil.WriteFile("./tmp.go", preamble, 0644)
}
