// NOTICE
// This file was automatically generated by ../../generators/models.go. Do not edit it!
// You can regenerate it by running 'go generate ./models' from the directory above.

package model801

import (
	"github.com/crabmusket/gosunspec"
	"github.com/crabmusket/gosunspec/smdx"
	"github.com/crabmusket/gosunspec/typelabel"
)

// Block801 - Energy Storage Base Model (DEPRECATED) - This model has been deprecated.

const (
	ModelID = 801
)

const (
	DEPRECATED = "DEPRECATED"
)

type Block801 struct {
	DEPRECATED sunspec.Enum16 `sunspec:"offset=0"`
}

func (self *Block801) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	smdx.RegisterModel(&smdx.ModelElement{
		Id:     ModelID,
		Name:   "storage",
		Length: 1,
		Blocks: []smdx.BlockElement{
			smdx.BlockElement{
				Length: 1,

				Points: []smdx.PointElement{
					smdx.PointElement{Id: DEPRECATED, Offset: 0, Type: typelabel.Enum16, Mandatory: true},
				},
			},
		}})
}
