// NOTICE
// This file was automatically generated by ../../generators/models.go. Do not edit it!
// You can regenerate it by running 'go generate ./models' from the directory above.

package model134

import (
	"github.com/crabmusket/gosunspec"
	"github.com/crabmusket/gosunspec/smdx"
	"github.com/crabmusket/gosunspec/typelabel"
)

// Block134 - Freq-Watt Crv - Curve-Based Frequency-Watt

const (
	ModelID = 134
)

const (
	ActCrv       = "ActCrv"
	ActPt        = "ActPt"
	CrvNam       = "CrvNam"
	Hz1          = "Hz1"
	Hz10         = "Hz10"
	Hz11         = "Hz11"
	Hz12         = "Hz12"
	Hz13         = "Hz13"
	Hz14         = "Hz14"
	Hz15         = "Hz15"
	Hz16         = "Hz16"
	Hz17         = "Hz17"
	Hz18         = "Hz18"
	Hz19         = "Hz19"
	Hz2          = "Hz2"
	Hz20         = "Hz20"
	Hz3          = "Hz3"
	Hz4          = "Hz4"
	Hz5          = "Hz5"
	Hz6          = "Hz6"
	Hz7          = "Hz7"
	Hz8          = "Hz8"
	Hz9          = "Hz9"
	Hz_SF        = "Hz_SF"
	ModEna       = "ModEna"
	NCrv         = "NCrv"
	NPt          = "NPt"
	ReadOnly     = "ReadOnly"
	RmpDecTmm    = "RmpDecTmm"
	RmpIncDec_SF = "RmpIncDec_SF"
	RmpIncTmm    = "RmpIncTmm"
	RmpPT1Tms    = "RmpPT1Tms"
	RmpRsUp      = "RmpRsUp"
	RmpTms       = "RmpTms"
	RvrtTms      = "RvrtTms"
	SnptW        = "SnptW"
	W1           = "W1"
	W10          = "W10"
	W11          = "W11"
	W12          = "W12"
	W13          = "W13"
	W14          = "W14"
	W15          = "W15"
	W16          = "W16"
	W17          = "W17"
	W18          = "W18"
	W19          = "W19"
	W2           = "W2"
	W20          = "W20"
	W3           = "W3"
	W4           = "W4"
	W5           = "W5"
	W6           = "W6"
	W7           = "W7"
	W8           = "W8"
	W9           = "W9"
	WRef         = "WRef"
	WRefStopHz   = "WRefStopHz"
	WRefStrHz    = "WRefStrHz"
	W_SF         = "W_SF"
	WinTms       = "WinTms"
)

type Block134Repeat struct {
	ActPt      uint16             `sunspec:"offset=0,len=1,access=rw"`
	Hz1        uint16             `sunspec:"offset=1,len=1,sf=Hz_SF,access=rw"`
	W1         int16              `sunspec:"offset=2,len=1,sf=W_SF,access=rw"`
	Hz2        uint16             `sunspec:"offset=3,len=1,sf=Hz_SF,access=rw"`
	W2         int16              `sunspec:"offset=4,len=1,sf=W_SF,access=rw"`
	Hz3        uint16             `sunspec:"offset=5,len=1,sf=Hz_SF,access=rw"`
	W3         int16              `sunspec:"offset=6,len=1,sf=W_SF,access=rw"`
	Hz4        uint16             `sunspec:"offset=7,len=1,sf=Hz_SF,access=rw"`
	W4         int16              `sunspec:"offset=8,len=1,sf=W_SF,access=rw"`
	Hz5        uint16             `sunspec:"offset=9,len=1,sf=Hz_SF,access=rw"`
	W5         int16              `sunspec:"offset=10,len=1,sf=W_SF,access=rw"`
	Hz6        uint16             `sunspec:"offset=11,len=1,sf=Hz_SF,access=rw"`
	W6         int16              `sunspec:"offset=12,len=1,sf=W_SF,access=rw"`
	Hz7        uint16             `sunspec:"offset=13,len=1,sf=Hz_SF,access=rw"`
	W7         int16              `sunspec:"offset=14,len=1,sf=W_SF,access=rw"`
	Hz8        uint16             `sunspec:"offset=15,len=1,sf=Hz_SF,access=rw"`
	W8         int16              `sunspec:"offset=16,len=1,sf=W_SF,access=rw"`
	Hz9        uint16             `sunspec:"offset=17,len=1,sf=Hz_SF,access=rw"`
	W9         int16              `sunspec:"offset=18,len=1,sf=W_SF,access=rw"`
	Hz10       uint16             `sunspec:"offset=19,len=1,sf=Hz_SF,access=rw"`
	W10        int16              `sunspec:"offset=20,len=1,sf=W_SF,access=rw"`
	Hz11       uint16             `sunspec:"offset=21,len=1,sf=Hz_SF,access=rw"`
	W11        int16              `sunspec:"offset=22,len=1,sf=W_SF,access=rw"`
	Hz12       uint16             `sunspec:"offset=23,len=1,sf=Hz_SF,access=rw"`
	W12        int16              `sunspec:"offset=24,len=1,sf=W_SF,access=rw"`
	Hz13       uint16             `sunspec:"offset=25,len=1,sf=Hz_SF,access=rw"`
	W13        int16              `sunspec:"offset=26,len=1,sf=W_SF,access=rw"`
	Hz14       uint16             `sunspec:"offset=27,len=1,sf=Hz_SF,access=rw"`
	W14        int16              `sunspec:"offset=28,len=1,sf=W_SF,access=rw"`
	Hz15       uint16             `sunspec:"offset=29,len=1,sf=Hz_SF,access=rw"`
	W15        int16              `sunspec:"offset=30,len=1,sf=W_SF,access=rw"`
	Hz16       uint16             `sunspec:"offset=31,len=1,sf=Hz_SF,access=rw"`
	W16        int16              `sunspec:"offset=32,len=1,sf=W_SF,access=rw"`
	Hz17       uint16             `sunspec:"offset=33,len=1,sf=Hz_SF,access=rw"`
	W17        int16              `sunspec:"offset=34,len=1,sf=W_SF,access=rw"`
	Hz18       uint16             `sunspec:"offset=35,len=1,sf=Hz_SF,access=rw"`
	W18        int16              `sunspec:"offset=36,len=1,sf=W_SF,access=rw"`
	Hz19       uint16             `sunspec:"offset=37,len=1,sf=Hz_SF,access=rw"`
	W19        int16              `sunspec:"offset=38,len=1,sf=W_SF,access=rw"`
	Hz20       uint16             `sunspec:"offset=39,len=1,sf=Hz_SF,access=rw"`
	W20        int16              `sunspec:"offset=40,len=1,sf=W_SF,access=rw"`
	CrvNam     string             `sunspec:"offset=41,len=8,access=rw"`
	RmpPT1Tms  uint16             `sunspec:"offset=49,len=1,access=rw"`
	RmpDecTmm  uint16             `sunspec:"offset=50,len=1,sf=RmpIncDec_SF,access=rw"`
	RmpIncTmm  uint16             `sunspec:"offset=51,len=1,sf=RmpIncDec_SF,access=rw"`
	RmpRsUp    uint16             `sunspec:"offset=52,len=1,sf=RmpIncDec_SF,access=rw"`
	SnptW      sunspec.Bitfield16 `sunspec:"offset=53,len=1,access=rw"`
	WRef       uint16             `sunspec:"offset=54,len=1,sf=W_SF,access=rw"`
	WRefStrHz  uint16             `sunspec:"offset=55,len=1,sf=Hz_SF,access=rw"`
	WRefStopHz uint16             `sunspec:"offset=56,len=1,sf=Hz_SF,access=rw"`
	ReadOnly   sunspec.Enum16     `sunspec:"offset=57,len=1,access=r"`
}

type Block134 struct {
	ActCrv       uint16              `sunspec:"offset=0,len=1,access=rw"`
	ModEna       sunspec.Bitfield16  `sunspec:"offset=1,len=1,access=rw"`
	WinTms       uint16              `sunspec:"offset=2,len=1,access=rw"`
	RvrtTms      uint16              `sunspec:"offset=3,len=1,access=rw"`
	RmpTms       uint16              `sunspec:"offset=4,len=1,access=rw"`
	NCrv         uint16              `sunspec:"offset=5,len=1,access=r"`
	NPt          uint16              `sunspec:"offset=6,len=1,access=r"`
	Hz_SF        sunspec.ScaleFactor `sunspec:"offset=7,len=1,access=r"`
	W_SF         sunspec.ScaleFactor `sunspec:"offset=8,len=1,access=r"`
	RmpIncDec_SF sunspec.ScaleFactor `sunspec:"offset=9,len=1,access=r"`

	Repeats []Block134Repeat
}

func (self *Block134) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	smdx.RegisterModel(&smdx.ModelElement{
		Id:     ModelID,
		Name:   "freq_watt",
		Length: 68,
		Blocks: []smdx.BlockElement{
			smdx.BlockElement{
				Length: 10,
				Type:   "fixed",
				Points: []smdx.PointElement{
					smdx.PointElement{Id: ActCrv, Offset: 0, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					smdx.PointElement{Id: ModEna, Offset: 1, Type: typelabel.Bitfield16, Access: "rw", Length: 1, Mandatory: true},
					smdx.PointElement{Id: WinTms, Offset: 2, Type: typelabel.Uint16, Units: "Secs", Access: "rw", Length: 1},
					smdx.PointElement{Id: RvrtTms, Offset: 3, Type: typelabel.Uint16, Units: "Secs", Access: "rw", Length: 1},
					smdx.PointElement{Id: RmpTms, Offset: 4, Type: typelabel.Uint16, Units: "Secs", Access: "rw", Length: 1},
					smdx.PointElement{Id: NCrv, Offset: 5, Type: typelabel.Uint16, Access: "r", Length: 1, Mandatory: true},
					smdx.PointElement{Id: NPt, Offset: 6, Type: typelabel.Uint16, Access: "r", Length: 1, Mandatory: true},
					smdx.PointElement{Id: Hz_SF, Offset: 7, Type: typelabel.ScaleFactor, Units: "SF", Access: "r", Length: 1, Mandatory: true},
					smdx.PointElement{Id: W_SF, Offset: 8, Type: typelabel.ScaleFactor, Units: "SF", Access: "r", Length: 1, Mandatory: true},
					smdx.PointElement{Id: RmpIncDec_SF, Offset: 9, Type: typelabel.ScaleFactor, Units: "SF", Access: "r", Length: 1},
				},
			},
			smdx.BlockElement{Name: "curve",
				Length: 58,
				Type:   "repeating",
				Points: []smdx.PointElement{
					smdx.PointElement{Id: ActPt, Offset: 0, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					smdx.PointElement{Id: Hz1, Offset: 1, Type: typelabel.Uint16, ScaleFactor: "Hz_SF", Units: "Hz", Access: "rw", Length: 1, Mandatory: true},
					smdx.PointElement{Id: W1, Offset: 2, Type: typelabel.Int16, ScaleFactor: "W_SF", Units: "% WRef", Access: "rw", Length: 1, Mandatory: true},
					smdx.PointElement{Id: Hz2, Offset: 3, Type: typelabel.Uint16, ScaleFactor: "Hz_SF", Units: "Hz", Access: "rw", Length: 1},
					smdx.PointElement{Id: W2, Offset: 4, Type: typelabel.Int16, ScaleFactor: "W_SF", Units: "% WRef", Access: "rw", Length: 1},
					smdx.PointElement{Id: Hz3, Offset: 5, Type: typelabel.Uint16, ScaleFactor: "Hz_SF", Units: "Hz", Access: "rw", Length: 1},
					smdx.PointElement{Id: W3, Offset: 6, Type: typelabel.Int16, ScaleFactor: "W_SF", Units: "% WRef", Access: "rw", Length: 1},
					smdx.PointElement{Id: Hz4, Offset: 7, Type: typelabel.Uint16, ScaleFactor: "Hz_SF", Units: "Hz", Access: "rw", Length: 1},
					smdx.PointElement{Id: W4, Offset: 8, Type: typelabel.Int16, ScaleFactor: "W_SF", Units: "% WRef", Access: "rw", Length: 1},
					smdx.PointElement{Id: Hz5, Offset: 9, Type: typelabel.Uint16, ScaleFactor: "Hz_SF", Units: "Hz", Access: "rw", Length: 1},
					smdx.PointElement{Id: W5, Offset: 10, Type: typelabel.Int16, ScaleFactor: "W_SF", Units: "% WRef", Access: "rw", Length: 1},
					smdx.PointElement{Id: Hz6, Offset: 11, Type: typelabel.Uint16, ScaleFactor: "Hz_SF", Units: "Hz", Access: "rw", Length: 1},
					smdx.PointElement{Id: W6, Offset: 12, Type: typelabel.Int16, ScaleFactor: "W_SF", Units: "% WRef", Access: "rw", Length: 1},
					smdx.PointElement{Id: Hz7, Offset: 13, Type: typelabel.Uint16, ScaleFactor: "Hz_SF", Units: "Hz", Access: "rw", Length: 1},
					smdx.PointElement{Id: W7, Offset: 14, Type: typelabel.Int16, ScaleFactor: "W_SF", Units: "% WRef", Access: "rw", Length: 1},
					smdx.PointElement{Id: Hz8, Offset: 15, Type: typelabel.Uint16, ScaleFactor: "Hz_SF", Units: "Hz", Access: "rw", Length: 1},
					smdx.PointElement{Id: W8, Offset: 16, Type: typelabel.Int16, ScaleFactor: "W_SF", Units: "% WRef", Access: "rw", Length: 1},
					smdx.PointElement{Id: Hz9, Offset: 17, Type: typelabel.Uint16, ScaleFactor: "Hz_SF", Units: "Hz", Access: "rw", Length: 1},
					smdx.PointElement{Id: W9, Offset: 18, Type: typelabel.Int16, ScaleFactor: "W_SF", Units: "% WRef", Access: "rw", Length: 1},
					smdx.PointElement{Id: Hz10, Offset: 19, Type: typelabel.Uint16, ScaleFactor: "Hz_SF", Units: "Hz", Access: "rw", Length: 1},
					smdx.PointElement{Id: W10, Offset: 20, Type: typelabel.Int16, ScaleFactor: "W_SF", Units: "% WRef", Access: "rw", Length: 1},
					smdx.PointElement{Id: Hz11, Offset: 21, Type: typelabel.Uint16, ScaleFactor: "Hz_SF", Units: "Hz", Access: "rw", Length: 1},
					smdx.PointElement{Id: W11, Offset: 22, Type: typelabel.Int16, ScaleFactor: "W_SF", Units: "% WRef", Access: "rw", Length: 1},
					smdx.PointElement{Id: Hz12, Offset: 23, Type: typelabel.Uint16, ScaleFactor: "Hz_SF", Units: "Hz", Access: "rw", Length: 1},
					smdx.PointElement{Id: W12, Offset: 24, Type: typelabel.Int16, ScaleFactor: "W_SF", Units: "% WRef", Access: "rw", Length: 1},
					smdx.PointElement{Id: Hz13, Offset: 25, Type: typelabel.Uint16, ScaleFactor: "Hz_SF", Units: "Hz", Access: "rw", Length: 1},
					smdx.PointElement{Id: W13, Offset: 26, Type: typelabel.Int16, ScaleFactor: "W_SF", Units: "% WRef", Access: "rw", Length: 1},
					smdx.PointElement{Id: Hz14, Offset: 27, Type: typelabel.Uint16, ScaleFactor: "Hz_SF", Units: "Hz", Access: "rw", Length: 1},
					smdx.PointElement{Id: W14, Offset: 28, Type: typelabel.Int16, ScaleFactor: "W_SF", Units: "% WRef", Access: "rw", Length: 1},
					smdx.PointElement{Id: Hz15, Offset: 29, Type: typelabel.Uint16, ScaleFactor: "Hz_SF", Units: "Hz", Access: "rw", Length: 1},
					smdx.PointElement{Id: W15, Offset: 30, Type: typelabel.Int16, ScaleFactor: "W_SF", Units: "% WRef", Access: "rw", Length: 1},
					smdx.PointElement{Id: Hz16, Offset: 31, Type: typelabel.Uint16, ScaleFactor: "Hz_SF", Units: "Hz", Access: "rw", Length: 1},
					smdx.PointElement{Id: W16, Offset: 32, Type: typelabel.Int16, ScaleFactor: "W_SF", Units: "% WRef", Access: "rw", Length: 1},
					smdx.PointElement{Id: Hz17, Offset: 33, Type: typelabel.Uint16, ScaleFactor: "Hz_SF", Units: "Hz", Access: "rw", Length: 1},
					smdx.PointElement{Id: W17, Offset: 34, Type: typelabel.Int16, ScaleFactor: "W_SF", Units: "% WRef", Access: "rw", Length: 1},
					smdx.PointElement{Id: Hz18, Offset: 35, Type: typelabel.Uint16, ScaleFactor: "Hz_SF", Units: "Hz", Access: "rw", Length: 1},
					smdx.PointElement{Id: W18, Offset: 36, Type: typelabel.Int16, ScaleFactor: "W_SF", Units: "% WRef", Access: "rw", Length: 1},
					smdx.PointElement{Id: Hz19, Offset: 37, Type: typelabel.Uint16, ScaleFactor: "Hz_SF", Units: "Hz", Access: "rw", Length: 1},
					smdx.PointElement{Id: W19, Offset: 38, Type: typelabel.Int16, ScaleFactor: "W_SF", Units: "% WRef", Access: "rw", Length: 1},
					smdx.PointElement{Id: Hz20, Offset: 39, Type: typelabel.Uint16, ScaleFactor: "Hz_SF", Units: "Hz", Access: "rw", Length: 1},
					smdx.PointElement{Id: W20, Offset: 40, Type: typelabel.Int16, ScaleFactor: "W_SF", Units: "% WRef", Access: "rw", Length: 1},
					smdx.PointElement{Id: CrvNam, Offset: 41, Type: typelabel.String, Access: "rw", Length: 8},
					smdx.PointElement{Id: RmpPT1Tms, Offset: 49, Type: typelabel.Uint16, Units: "Secs", Access: "rw", Length: 1},
					smdx.PointElement{Id: RmpDecTmm, Offset: 50, Type: typelabel.Uint16, ScaleFactor: "RmpIncDec_SF", Units: "% WMax/min", Access: "rw", Length: 1},
					smdx.PointElement{Id: RmpIncTmm, Offset: 51, Type: typelabel.Uint16, ScaleFactor: "RmpIncDec_SF", Units: "% WMax/min", Access: "rw", Length: 1},
					smdx.PointElement{Id: RmpRsUp, Offset: 52, Type: typelabel.Uint16, ScaleFactor: "RmpIncDec_SF", Units: "% WMax/min", Access: "rw", Length: 1},
					smdx.PointElement{Id: SnptW, Offset: 53, Type: typelabel.Bitfield16, Access: "rw", Length: 1, Mandatory: true},
					smdx.PointElement{Id: WRef, Offset: 54, Type: typelabel.Uint16, ScaleFactor: "W_SF", Units: "W", Access: "rw", Length: 1},
					smdx.PointElement{Id: WRefStrHz, Offset: 55, Type: typelabel.Uint16, ScaleFactor: "Hz_SF", Units: "Hz", Access: "rw", Length: 1},
					smdx.PointElement{Id: WRefStopHz, Offset: 56, Type: typelabel.Uint16, ScaleFactor: "Hz_SF", Units: "Hz", Access: "rw", Length: 1},
					smdx.PointElement{Id: ReadOnly, Offset: 57, Type: typelabel.Enum16, Access: "r", Length: 1, Mandatory: true},
				},
			},
		}})
}
